# HW7 — Time-Series Features and JSONB in PostgreSQL

This notebook implements the required time-series feature engineering,
JSONB event-log queries, index experiments, query-plan analysis,
and JSONB-versus-normalized comparison.

**Data source:** NYC TLC Yellow Taxi trip data for March 2024.
If the official Parquet dataset cannot be downloaded, a deterministic
synthetic dataset is used and explicitly reported.

## 1. Environment setup

The assignment specifies `pgserver`. The notebook tries `pgserver` first
and falls back to a local PostgreSQL 16 service if necessary.

In [13]:
%pip install -q psycopg2-binary sqlalchemy pandas pyarrow requests

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 17.3 MB/s eta 0:00:00

In [2]:
import os
import subprocess
from urllib.request import urlretrieve

import pandas as pd
from sqlalchemy import create_engine, text
from IPython.display import display, Markdown

engine = None
pg = None
USE_PGSERVER = False

try:
    import pgserver
    pg = pgserver.get_server("/tmp/hw7_pg", cleanup_mode="stop")
    engine = create_engine(pg.get_uri(), future=True)

    with engine.connect() as conn:
        print(conn.execute(text("SELECT version()")).scalar_one())

    USE_PGSERVER = True
    print("Connected through pgserver.")

except Exception as exc:
    print("pgserver startup failed:", repr(exc))
    print("Using PostgreSQL 16 system-service fallback.")

    subprocess.run(
        "apt-get update -qq && apt-get install -y postgresql-16 postgresql-client-16",
        shell=True,
        check=True
    )
    subprocess.run("service postgresql start", shell=True, check=True)
    subprocess.run(
        "su postgres -c \"psql -c \\\"ALTER USER postgres PASSWORD 'postgres';\\\"\"",
        shell=True,
        check=True
    )

    engine = create_engine(
        "postgresql+psycopg2://postgres:postgres@localhost:5432/postgres",
        future=True
    )

    with engine.connect() as conn:
        print(conn.execute(text("SELECT version()")).scalar_one())


def read_df(sql, params=None):
    with engine.connect() as conn:
        return pd.read_sql_query(text(sql), conn, params=params)


def run_sql(sql):
    with engine.begin() as conn:
        conn.exec_driver_sql(sql)


print("Database connection initialized.")

pgserver startup failed: ModuleNotFoundError("No module named 'pgserver'")
Using PostgreSQL 16 system-service fallback.
PostgreSQL 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0, 64-bit
Database connection initialized.

## 2. Task 1 — Load NYC Taxi data

Download the official TLC Yellow Taxi Parquet file for March 2024.
At most 500,000 rows are loaded to keep the notebook manageable.
If download or loading fails, the notebook uses the deterministic fallback.

In [3]:
URL = (
    "https://d37ci6vzurychx.cloudfront.net/trip-data/"
    "yellow_tripdata_2024-03.parquet"
)
parquet_path = "/content/yellow_tripdata_2024-03.parquet"
USE_REAL_DATA = False
taxi = None

try:
    print("Downloading official NYC TLC data...")
    urlretrieve(URL, parquet_path)

    columns = [
        "tpep_pickup_datetime",
        "tpep_dropoff_datetime",
        "PULocationID",
        "DOLocationID",
        "trip_distance",
        "fare_amount",
        "passenger_count",
    ]

    taxi = pd.read_parquet(parquet_path, columns=columns).head(500_000)

    taxi = taxi[
        (taxi["fare_amount"] > 0)
        & (taxi["fare_amount"] < 500)
        & (taxi["trip_distance"] > 0)
        & (taxi["trip_distance"] < 100)
        & taxi["PULocationID"].notna()
        & taxi["tpep_pickup_datetime"].notna()
    ].copy()

    USE_REAL_DATA = not taxi.empty
    print("Rows after cleaning:", len(taxi))

except Exception as exc:
    print("Official data unavailable:", type(exc).__name__, str(exc)[:300])
    print("The notebook will use the synthetic fallback.")

print("Using real TLC data:", USE_REAL_DATA)

Downloading official NYC TLC data...
Rows after cleaning: 486964
Using real TLC data: True

### Load source data into PostgreSQL

In [4]:
if USE_REAL_DATA:
    taxi.to_sql(
        "nyc_taxi_raw",
        engine,
        if_exists="replace",
        index=False,
        chunksize=2000,
    )

    display(read_df("SELECT COUNT(*) AS n_rows FROM nyc_taxi_raw"))
else:
    run_sql("""
    DROP TABLE IF EXISTS nyc_taxi_raw;
    CREATE TABLE nyc_taxi_raw (
        "tpep_pickup_datetime" TIMESTAMP,
        "tpep_dropoff_datetime" TIMESTAMP,
        "PULocationID" INTEGER,
        "DOLocationID" INTEGER,
        trip_distance NUMERIC(10,2),
        fare_amount NUMERIC(10,2),
        passenger_count INTEGER
    );
    """)
    print("Created an empty source schema for fallback mode.")

   n_rows
0  486964

### Create `t7_hw_taxi_daily`

The daily aggregation is grouped by pickup zone and date.
The fallback contains 60 days across five zones (300 rows).

In [5]:
if USE_REAL_DATA:
    run_sql("""
    DROP TABLE IF EXISTS t7_hw_taxi_daily;

    CREATE TABLE t7_hw_taxi_daily AS
    SELECT
        "PULocationID"::INTEGER AS pickup_zone_id,
        DATE_TRUNC(
            'day', "tpep_pickup_datetime"::TIMESTAMP
        )::DATE AS ts_day,
        COUNT(*)::INTEGER AS trip_count,
        AVG(fare_amount)::NUMERIC(10,2) AS avg_fare,
        SUM(trip_distance)::NUMERIC(12,2) AS total_distance
    FROM nyc_taxi_raw
    WHERE fare_amount > 0
      AND fare_amount < 500
      AND trip_distance > 0
      AND trip_distance < 100
      AND "PULocationID" IS NOT NULL
      AND "tpep_pickup_datetime" IS NOT NULL
    GROUP BY
        "PULocationID"::INTEGER,
        DATE_TRUNC(
            'day', "tpep_pickup_datetime"::TIMESTAMP
        )::DATE;

    ALTER TABLE t7_hw_taxi_daily
        ADD PRIMARY KEY (pickup_zone_id, ts_day);
    """)
else:
    run_sql("""
    DROP TABLE IF EXISTS t7_hw_taxi_daily;

    CREATE TABLE t7_hw_taxi_daily (
        pickup_zone_id INTEGER NOT NULL,
        ts_day DATE NOT NULL,
        trip_count INTEGER NOT NULL CHECK (trip_count >= 0),
        avg_fare NUMERIC(10,2) NOT NULL CHECK (avg_fare >= 0),
        total_distance NUMERIC(12,2) NOT NULL CHECK (total_distance >= 0),
        PRIMARY KEY (pickup_zone_id, ts_day)
    );

    INSERT INTO t7_hw_taxi_daily (
        pickup_zone_id, ts_day, trip_count, avg_fare, total_distance
    )
    SELECT
        z.zone_id,
        DATE '2024-03-31' - (59 - n),
        500 + n * 7 + z.zone_id * 50 + (n % 5) * 30,
        (12.5 + z.zone_id * 0.7 + (n % 4) * 0.4)::NUMERIC(10,2),
        (1500 + n * 25 + z.zone_id * 120)::NUMERIC(12,2)
    FROM generate_series(0,59) AS n
    CROSS JOIN (VALUES (1),(2),(3),(4),(5)) AS z(zone_id);
    """)

display(read_df("""
SELECT pickup_zone_id, COUNT(*) AS n_days
FROM t7_hw_taxi_daily
GROUP BY pickup_zone_id
ORDER BY pickup_zone_id
"""))

display(read_df("SELECT COUNT(*) AS total_daily_rows FROM t7_hw_taxi_daily"))

     pickup_zone_id  n_days
0                 1       5
1                 3       6
2                 4       6
3                 6       4
4                 7       6
..              ...     ...
235             261       6
236             262       6
237             263       7
238             264       6
239             265       6

[240 rows x 2 columns]

   total_daily_rows
0              1217

### Optional typed timestamp table

This demonstration uses `TIMESTAMPTZ` to preserve the pickup/drop-off
instant using the `America/New_York` time zone. It is created only
when the real TLC data is available.

In [6]:
if USE_REAL_DATA:
    run_sql("""
    DROP TABLE IF EXISTS t7_hw_taxi_trips_typed;

    CREATE TABLE t7_hw_taxi_trips_typed AS
    SELECT
        "PULocationID"::INTEGER AS pickup_zone_id,
        "DOLocationID"::INTEGER AS dropoff_zone_id,
        (
            "tpep_pickup_datetime"::TIMESTAMP
            AT TIME ZONE 'America/New_York'
        ) AS pickup_at,
        (
            "tpep_dropoff_datetime"::TIMESTAMP
            AT TIME ZONE 'America/New_York'
        ) AS dropoff_at,
        trip_distance::NUMERIC(10,2) AS trip_distance,
        fare_amount::NUMERIC(10,2) AS fare_amount,
        passenger_count::INTEGER AS passenger_count
    FROM nyc_taxi_raw
    WHERE fare_amount > 0 AND fare_amount < 500
      AND trip_distance > 0 AND trip_distance < 100;
    """)

    display(read_df("""
    SELECT pickup_at, pg_typeof(pickup_at) AS pickup_type
    FROM t7_hw_taxi_trips_typed
    LIMIT 5
    """))
else:
    print("Skipped: real TLC source data was not loaded.")

                  pickup_at               pickup_type
0 2024-03-01 05:18:51+00:00  timestamp with time zone
1 2024-03-01 05:26:00+00:00  timestamp with time zone
2 2024-03-01 05:09:22+00:00  timestamp with time zone
3 2024-03-01 05:33:45+00:00  timestamp with time zone
4 2024-03-01 05:05:43+00:00  timestamp with time zone

## 3. Task 2 — Time-series ML features

All window functions partition by `pickup_zone_id`.
This prevents history from one zone leaking into another zone's features.

### Feature 1 — Lag features: 1, 7, and 30 days

In [7]:
display(read_df("""
SELECT
    pickup_zone_id,
    ts_day,
    trip_count,
    LAG(trip_count, 1) OVER w AS trips_lag_1d,
    LAG(trip_count, 7) OVER w AS trips_lag_7d,
    LAG(trip_count, 30) OVER w AS trips_lag_30d
FROM t7_hw_taxi_daily
WINDOW w AS (
    PARTITION BY pickup_zone_id
    ORDER BY ts_day
)
ORDER BY pickup_zone_id, ts_day
LIMIT 20
"""))

,pickup_zone_id,ts_day,trip_count,trips_lag_1d,trips_lag_7d,trips_lag_30d
0,1,2024-03-01,1,NaN,None,None
1,1,2024-03-02,2,1.0,None,None
2,1,2024-03-03,2,2.0,None,None
3,1,2024-03-04,1,2.0,None,None
4,1,2024-03-05,1,1.0,None,None
5,3,2024-03-01,3,NaN,None,None
6,3,2024-03-02,1,3.0,None,None
7,3,2024-03-03,4,1.0,None,None
8,3,2024-03-04,2,4.0,None,None
9,3,2024-03-05,1,2.0,None,None
10,3,2024-03-06,1,1.0,None,None
11,4,2024-03-01,108,NaN,None,None
12,4,2024-03-02,273,108.0,None,None
13,4,2024-03-03,204,273.0,None,None
14,4,2024-03-04,25,204.0,None,None
15,4,2024-03-05,44,25.0,None,None
16,4,2024-03-06,11,44.0,None,None
17,6,2024-03-01,1,NaN,None,None
18,6,2024-03-02,1,1.0,None,None
19,6,2024-03-03,1,1.0,None,None

### Feature 2 — Rolling 7-day average fare

In [8]:
display(read_df("""
SELECT
    pickup_zone_id,
    ts_day,
    avg_fare,
    AVG(avg_fare) OVER w7 AS rolling_avg_fare_7d,
    COUNT(*) OVER w7 AS days_in_window
FROM t7_hw_taxi_daily
WINDOW w7 AS (
    PARTITION BY pickup_zone_id
    ORDER BY ts_day::TIMESTAMP
    RANGE BETWEEN INTERVAL '6 days' PRECEDING AND CURRENT ROW
)
ORDER BY pickup_zone_id, ts_day
LIMIT 20
"""))

    pickup_zone_id      ts_day  avg_fare  rolling_avg_fare_7d  days_in_window
0                1  2024-03-01    105.00           105.000000               1
1                1  2024-03-02     95.00           100.000000               2
2                1  2024-03-03     51.00            83.666667               3
3                1  2024-03-04     40.00            72.750000               4
4                1  2024-03-05    120.00            82.200000               5
5                3  2024-03-01     39.17            39.170000               1
6                3  2024-03-02     21.50            30.335000               2
7                3  2024-03-03     25.03            28.566667               3
8                3  2024-03-04     39.15            31.212500               4
9                3  2024-03-05     45.50            34.070000               5
10               3  2024-03-06     53.50            37.308333               6
11               4  2024-03-01     16.38            16.380000               1
12               4  2024-03-02     15.84            16.110000               2
13               4  2024-03-03     16.35            16.190000               3
14               4  2024-03-04     21.84            17.602500               4
15               4  2024-03-05     18.07            17.696000               5
16               4  2024-03-06     20.05            18.088333               6
17               6  2024-03-01      1.00             1.000000               1
18               6  2024-03-02      1.00             1.000000               2
19               6  2024-03-03      1.00             1.000000               3

### Feature 3 — Rolling 30-day fare volatility

In [9]:
display(read_df("""
SELECT
    pickup_zone_id,
    ts_day,
    avg_fare,
    STDDEV_SAMP(avg_fare) OVER w30 AS rolling_std_fare_30d,
    COUNT(*) OVER w30 AS days_in_window
FROM t7_hw_taxi_daily
WINDOW w30 AS (
    PARTITION BY pickup_zone_id
    ORDER BY ts_day::TIMESTAMP
    RANGE BETWEEN INTERVAL '29 days' PRECEDING AND CURRENT ROW
)
ORDER BY pickup_zone_id, ts_day
LIMIT 20
"""))

    pickup_zone_id      ts_day  avg_fare  rolling_std_fare_30d  days_in_window
0                1  2024-03-01    105.00                   NaN               1
1                1  2024-03-02     95.00              7.071068               2
2                1  2024-03-03     51.00             28.728615               3
3                1  2024-03-04     40.00             32.045541               4
4                1  2024-03-05    120.00             34.881227               5
5                3  2024-03-01     39.17                   NaN               1
6                3  2024-03-02     21.50             12.494577               2
7                3  2024-03-03     25.03              9.350841               3
8                3  2024-03-04     39.15              9.289451               4
9                3  2024-03-05     45.50             10.273605               5
10               3  2024-03-06     53.50             12.139126               6
11               4  2024-03-01     16.38                   NaN               1
12               4  2024-03-02     15.84              0.381838               2
13               4  2024-03-03     16.35              0.303480               3
14               4  2024-03-04     21.84              2.835846               4
15               4  2024-03-05     18.07              2.464798               5
16               4  2024-03-06     20.05              2.404940               6
17               6  2024-03-01      1.00                   NaN               1
18               6  2024-03-02      1.00              0.000000               2
19               6  2024-03-03      1.00              0.000000               3

### Feature 4 — Expanding cumulative trips

In [10]:
display(read_df("""
SELECT
    pickup_zone_id,
    ts_day,
    trip_count,
    SUM(trip_count) OVER we AS cumulative_trips,
    AVG(trip_count) OVER we AS expanding_avg_trips
FROM t7_hw_taxi_daily
WINDOW we AS (
    PARTITION BY pickup_zone_id
    ORDER BY ts_day
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
)
ORDER BY pickup_zone_id, ts_day
LIMIT 20
"""))

,pickup_zone_id,ts_day,trip_count,cumulative_trips,expanding_avg_trips
0,1,2024-03-01,1,1,1.000000
1,1,2024-03-02,2,3,1.500000
2,1,2024-03-03,2,5,1.666667
3,1,2024-03-04,1,6,1.500000
4,1,2024-03-05,1,7,1.400000
5,3,2024-03-01,3,3,3.000000
6,3,2024-03-02,1,4,2.000000
7,3,2024-03-03,4,8,2.666667
8,3,2024-03-04,2,10,2.500000
9,3,2024-03-05,1,11,2.200000
10,3,2024-03-06,1,12,2.000000
11,4,2024-03-01,108,108,108.000000
12,4,2024-03-02,273,381,190.500000
13,4,2024-03-03,204,585,195.000000
14,4,2024-03-04,25,610,152.500000
15,4,2024-03-05,44,654,130.800000
16,4,2024-03-06,11,665,110.833333
17,6,2024-03-01,1,1,1.000000
18,6,2024-03-02,1,2,1.000000
19,6,2024-03-03,1,3,1.000000

### Combined feature view

In [11]:
run_sql("""
CREATE OR REPLACE VIEW v_t7_hw_taxi_features AS
WITH features_basic AS (
    SELECT
        pickup_zone_id,
        ts_day,
        trip_count,
        avg_fare,
        total_distance,
        LAG(trip_count, 1) OVER w_pid AS trips_lag_1d,
        LAG(trip_count, 7) OVER w_pid AS trips_lag_7d,
        LAG(trip_count, 30) OVER w_pid AS trips_lag_30d,
        AVG(avg_fare) OVER w7 AS rolling_avg_fare_7d,
        STDDEV_SAMP(avg_fare) OVER w30 AS rolling_std_fare_30d,
        SUM(trip_count) OVER we AS cumulative_trips,
        AVG(trip_count) OVER we AS expanding_avg_trips
    FROM t7_hw_taxi_daily
    WINDOW
        w_pid AS (
            PARTITION BY pickup_zone_id ORDER BY ts_day
        ),
        w7 AS (
            PARTITION BY pickup_zone_id
            ORDER BY ts_day::TIMESTAMP
            RANGE BETWEEN INTERVAL '6 days' PRECEDING AND CURRENT ROW
        ),
        w30 AS (
            PARTITION BY pickup_zone_id
            ORDER BY ts_day::TIMESTAMP
            RANGE BETWEEN INTERVAL '29 days' PRECEDING AND CURRENT ROW
        ),
        we AS (
            PARTITION BY pickup_zone_id ORDER BY ts_day
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        )
)
SELECT *
FROM features_basic
WHERE trips_lag_30d IS NOT NULL;
""")

display(read_df("""
SELECT *
FROM v_t7_hw_taxi_features
ORDER BY pickup_zone_id, ts_day
LIMIT 20
"""))

Empty DataFrame
Columns: [pickup_zone_id, ts_day, trip_count, avg_fare, total_distance, trips_lag_1d, trips_lag_7d, trips_lag_30d, rolling_avg_fare_7d, rolling_std_fare_30d, cumulative_trips, expanding_avg_trips]
Index: []

## 4. Task 3 — JSONB event log

Create 50,000 synthetic events across five event types.
Each type has a different JSONB payload structure.

In [15]:

import psycopg2

# Reuse the connection settings from the existing SQLAlchemy engine.
url = engine.url

conn = psycopg2.connect(
    host=url.host,
    port=url.port or 5432,
    dbname=url.database,
    user=url.username,
    password=url.password,
)

try:
    with conn:
        with conn.cursor() as cur:
            cur.execute("DROP TABLE IF EXISTS t7_hw_events")

            cur.execute("""
                CREATE TABLE t7_hw_events (
                    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id INTEGER NOT NULL,
                    event_ts TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    event_type TEXT NOT NULL,
                    payload JSONB NOT NULL
                )
            """)

            cur.execute("""
                INSERT INTO t7_hw_events (
                    user_id, event_ts, event_type, payload
                )
                SELECT
                    (n % 1000) + 1,
                    TIMESTAMPTZ '2024-04-01 00:00:00+00'
                        - ((n % 60) || ' days')::INTERVAL,
                    CASE (n % 5)
                        WHEN 0 THEN 'page_view'
                        WHEN 1 THEN 'click'
                        WHEN 2 THEN 'add_to_cart'
                        WHEN 3 THEN 'checkout'
                        ELSE 'recommendation_shown'
                    END,
                    CASE (n % 5)
                        WHEN 0 THEN jsonb_build_object(
                            'url', '/product/' || ((n % 200) + 1),
                            'referrer',
                                (ARRAY['google','direct','email','fb'])[(n % 4) + 1],
                            'device',
                                (ARRAY['mobile','desktop','tablet'])[(n % 3) + 1]
                        )
                        WHEN 1 THEN jsonb_build_object(
                            'element_id', 'btn_' || ((n % 50) + 1),
                            'page_url', '/category/' || ((n % 20) + 1),
                            'device',
                                (ARRAY['mobile','desktop'])[(n % 2) + 1]
                        )
                        WHEN 2 THEN jsonb_build_object(
                            'product_id', (n % 200) + 1,
                            'price', ((n % 100) + 10)::NUMERIC(10,2),
                            'quantity', (n % 5) + 1,
                            'tags', jsonb_build_array(
                                (ARRAY['promo','new','clearance'])[(n % 3) + 1]
                            )
                        )
                        WHEN 3 THEN jsonb_build_object(
                            'order_id', 'o_' || (n + 100000),
                            'total', ((n % 500) + 50)::NUMERIC(10,2),
                            'items_count', (n % 10) + 1,
                            'payment_method',
                                (ARRAY['card','paypal','crypto'])[(n % 3) + 1]
                        )
                        ELSE jsonb_build_object(
                            'model_name', 'rec_v' || ((n % 5) + 1),
                            'model_version', '1.' || (n % 10),
                            'recommendations', jsonb_build_array(
                                (n % 200) + 1,
                                ((n + 1) % 200) + 1,
                                ((n + 2) % 200) + 1
                            ),
                            'experiment', 'exp_' || ((n % 3) + 1)
                        )
                    END
                FROM generate_series(1, 50000) AS n
            """)

            cur.execute("ANALYZE t7_hw_events")

    print("Created t7_hw_events and inserted 50,000 events.")

finally:
    conn.close()

display(read_df("""
    SELECT event_type, COUNT(*) AS n_events
    FROM t7_hw_events
    GROUP BY event_type
    ORDER BY event_type
"""))

Created t7_hw_events and inserted 50,000 events.

             event_type  n_events
0           add_to_cart     10000
1              checkout     10000
2                 click     10000
3             page_view     10000
4  recommendation_shown     10000

### JSONB Query 1 — Containment (`@>`)

In [16]:
display(read_df("""
SELECT event_id, user_id, event_ts, payload
FROM t7_hw_events
WHERE event_type = 'checkout'
  AND payload @> jsonb_build_object('payment_method', 'card')
LIMIT 10
"""))

,event_id,user_id,event_ts,payload
0,3,4,2024-03-29 00:00:00+00:00,"{'total': 53.0, 'order_id': 'o_100003', 'items..."
1,18,19,2024-03-14 00:00:00+00:00,"{'total': 68.0, 'order_id': 'o_100018', 'items..."
2,33,34,2024-02-28 00:00:00+00:00,"{'total': 83.0, 'order_id': 'o_100033', 'items..."
3,48,49,2024-02-13 00:00:00+00:00,"{'total': 98.0, 'order_id': 'o_100048', 'items..."
4,63,64,2024-03-29 00:00:00+00:00,"{'total': 113.0, 'order_id': 'o_100063', 'item..."
5,78,79,2024-03-14 00:00:00+00:00,"{'total': 128.0, 'order_id': 'o_100078', 'item..."
6,93,94,2024-02-28 00:00:00+00:00,"{'total': 143.0, 'order_id': 'o_100093', 'item..."
7,108,109,2024-02-13 00:00:00+00:00,"{'total': 158.0, 'order_id': 'o_100108', 'item..."
8,123,124,2024-03-29 00:00:00+00:00,"{'total': 173.0, 'order_id': 'o_100123', 'item..."
9,138,139,2024-03-14 00:00:00+00:00,"{'total': 188.0, 'order_id': 'o_100138', 'item..."

### JSONB Query 2 — Key existence (`?` and `?|`)

In [17]:
display(read_df("""
SELECT event_id, event_type, payload
FROM t7_hw_events
WHERE payload ? 'tags'
LIMIT 10
"""))

display(read_df("""
SELECT event_id, event_type, payload
FROM t7_hw_events
WHERE payload ?| ARRAY['experiment', 'model_version']
LIMIT 10
"""))

   event_id   event_type                                            payload
0         2  add_to_cart  {'tags': ['clearance'], 'price': 12.0, 'quanti...
1         7  add_to_cart  {'tags': ['new'], 'price': 17.0, 'quantity': 3...
2        12  add_to_cart  {'tags': ['promo'], 'price': 22.0, 'quantity':...
3        17  add_to_cart  {'tags': ['clearance'], 'price': 27.0, 'quanti...
4        22  add_to_cart  {'tags': ['new'], 'price': 32.0, 'quantity': 3...
5        27  add_to_cart  {'tags': ['promo'], 'price': 37.0, 'quantity':...
6        32  add_to_cart  {'tags': ['clearance'], 'price': 42.0, 'quanti...
7        37  add_to_cart  {'tags': ['new'], 'price': 47.0, 'quantity': 3...
8        42  add_to_cart  {'tags': ['promo'], 'price': 52.0, 'quantity':...
9        47  add_to_cart  {'tags': ['clearance'], 'price': 57.0, 'quanti...

,event_id,event_type,payload
0,4,recommendation_shown,"{'experiment': 'exp_2', 'model_name': 'rec_v5'..."
1,9,recommendation_shown,"{'experiment': 'exp_1', 'model_name': 'rec_v5'..."
2,14,recommendation_shown,"{'experiment': 'exp_3', 'model_name': 'rec_v5'..."
3,19,recommendation_shown,"{'experiment': 'exp_2', 'model_name': 'rec_v5'..."
4,24,recommendation_shown,"{'experiment': 'exp_1', 'model_name': 'rec_v5'..."
5,29,recommendation_shown,"{'experiment': 'exp_3', 'model_name': 'rec_v5'..."
6,34,recommendation_shown,"{'experiment': 'exp_2', 'model_name': 'rec_v5'..."
7,39,recommendation_shown,"{'experiment': 'exp_1', 'model_name': 'rec_v5'..."
8,44,recommendation_shown,"{'experiment': 'exp_3', 'model_name': 'rec_v5'..."
9,49,recommendation_shown,"{'experiment': 'exp_2', 'model_name': 'rec_v5'..."

### JSONB Query 3 — JSONPath

In [18]:
display(read_df("""
SELECT
    event_id,
    jsonb_path_query(payload, '$.recommendations[*]') AS recommended_pid
FROM t7_hw_events
WHERE event_type = 'recommendation_shown'
LIMIT 15
"""))

display(read_df("""
SELECT
    event_id,
    payload ->> 'order_id' AS order_id,
    (payload ->> 'total')::NUMERIC(10,2) AS total
FROM t7_hw_events
WHERE event_type = 'checkout'
  AND jsonb_path_exists(payload, '$.total ? (@ > 300)')
LIMIT 10
"""))

    event_id  recommended_pid
0          4                5
1          4                6
2          4                7
3          9               10
4          9               11
5          9               12
6         14               15
7         14               16
8         14               17
9         19               20
10        19               21
11        19               22
12        24               25
13        24               26
14        24               27

   event_id  order_id  total
0       253  o_100253  303.0
1       258  o_100258  308.0
2       263  o_100263  313.0
3       268  o_100268  318.0
4       273  o_100273  323.0
5       278  o_100278  328.0
6       283  o_100283  333.0
7       288  o_100288  338.0
8       293  o_100293  343.0
9       298  o_100298  348.0

## 5. Task 4 — GIN index and EXPLAIN ANALYZE

The notebook captures query plans before and after indexes.
The PostgreSQL planner may choose a sequential scan even when an index
exists; the actual plan must be discussed in the reflection.

### Step 1 — Containment query before GIN

In [19]:
run_sql("""
DROP INDEX IF EXISTS idx_t7_events_payload_gin_pathops;
DROP INDEX IF EXISTS idx_t7_events_payload_gin_ops;
DROP INDEX IF EXISTS idx_t7_events_device_btree;
ANALYZE t7_hw_events;
""")

display(read_df("""
EXPLAIN (ANALYZE, BUFFERS)
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload @> jsonb_build_object('payment_method', 'card')
"""))

                                          QUERY PLAN
0  Aggregate  (cost=1756.57..1756.58 rows=1 width...
1                           Buffers: shared hit=1000
2    ->  Seq Scan on t7_hw_events  (cost=0.00..17...
3          Filter: (payload @> jsonb_build_object...
4                      Rows Removed by Filter: 46666
5                           Buffers: shared hit=1000
6                                          Planning:
7                              Buffers: shared hit=9
8                            Planning Time: 0.173 ms
9                          Execution Time: 47.515 ms

### Step 2 — Create GIN index

In [20]:
run_sql("""
CREATE INDEX idx_t7_events_payload_gin_pathops
ON t7_hw_events USING GIN (payload jsonb_path_ops);
ANALYZE t7_hw_events;
""")

display(read_df("""
SELECT pg_size_pretty(
    pg_relation_size('idx_t7_events_payload_gin_pathops')
) AS gin_index_size
"""))

  gin_index_size
0        1144 kB

### Step 3 — Containment queries after GIN

In [21]:
display(read_df("""
EXPLAIN (ANALYZE, BUFFERS)
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload @> jsonb_build_object('payment_method', 'card')
"""))

display(read_df("""
EXPLAIN (ANALYZE, BUFFERS)
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload @> jsonb_build_object('referrer', 'google')
"""))

                                           QUERY PLAN
0   Aggregate  (cost=1114.36..1114.37 rows=1 width...
1                            Buffers: shared hit=1004
2     ->  Bitmap Heap Scan on t7_hw_events  (cost=...
3           Recheck Cond: (payload @> jsonb_build_...
4                             Heap Blocks: exact=1000
5                            Buffers: shared hit=1004
6           ->  Bitmap Index Scan on idx_t7_events...
7                 Index Cond: (payload @> jsonb_bu...
8                               Buffers: shared hit=4
9                                           Planning:
10                             Buffers: shared hit=17
11                            Planning Time: 0.333 ms
12                           Execution Time: 7.206 ms

                                           QUERY PLAN
0   Aggregate  (cost=1079.78..1079.79 rows=1 width...
1                            Buffers: shared hit=1004
2     ->  Bitmap Heap Scan on t7_hw_events  (cost=...
3           Recheck Cond: (payload @> jsonb_build_...
4                             Heap Blocks: exact=1000
5                            Buffers: shared hit=1004
6           ->  Bitmap Index Scan on idx_t7_events...
7                 Index Cond: (payload @> jsonb_bu...
8                               Buffers: shared hit=4
9                                           Planning:
10                              Buffers: shared hit=1
11                            Planning Time: 0.202 ms
12                           Execution Time: 5.729 ms

### Step 4 — Device equality before expression index

In [22]:
display(read_df("""
EXPLAIN (ANALYZE, BUFFERS)
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload ->> 'device' = 'mobile'
"""))

                                          QUERY PLAN
0  Aggregate  (cost=1750.62..1750.63 rows=1 width...
1                           Buffers: shared hit=1000
2    ->  Seq Scan on t7_hw_events  (cost=0.00..17...
3          Filter: ((payload ->> 'device'::text) ...
4                      Rows Removed by Filter: 41667
5                           Buffers: shared hit=1000
6                            Planning Time: 0.115 ms
7                          Execution Time: 10.869 ms

### Step 5 — Expression B-tree index and repeated query

In [23]:
run_sql("""
CREATE INDEX idx_t7_events_device_btree
ON t7_hw_events ((payload ->> 'device'));
ANALYZE t7_hw_events;
""")

display(read_df("""
EXPLAIN (ANALYZE, BUFFERS)
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload ->> 'device' = 'mobile'
"""))

                                           QUERY PLAN
0   Aggregate  (cost=1243.58..1243.59 rows=1 width...
1                     Buffers: shared hit=1000 read=9
2     ->  Bitmap Heap Scan on t7_hw_events  (cost=...
3           Recheck Cond: ((payload ->> 'device'::...
4                             Heap Blocks: exact=1000
5                     Buffers: shared hit=1000 read=9
6           ->  Bitmap Index Scan on idx_t7_events...
7                 Index Cond: ((payload ->> 'devic...
8                              Buffers: shared read=9
9                                           Planning:
10                      Buffers: shared hit=20 read=1
11                            Planning Time: 0.214 ms
12                           Execution Time: 3.545 ms

## 6. Task 5 — JSONB versus normalized checkout data

Create a typed relational table for checkout events and compare equivalent
aggregate queries using `EXPLAIN (ANALYZE, BUFFERS)`.

In [24]:
run_sql("""
DROP TABLE IF EXISTS t7_hw_checkouts_norm;

CREATE TABLE t7_hw_checkouts_norm (
    event_id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL,
    event_ts TIMESTAMPTZ NOT NULL,
    order_id TEXT NOT NULL,
    total NUMERIC(10,2) NOT NULL,
    items_count INTEGER NOT NULL CHECK (items_count > 0),
    payment_method TEXT NOT NULL
        CHECK (payment_method IN ('card', 'paypal', 'crypto'))
);

INSERT INTO t7_hw_checkouts_norm (
    event_id, user_id, event_ts, order_id,
    total, items_count, payment_method
)
SELECT
    event_id,
    user_id,
    event_ts,
    payload ->> 'order_id',
    (payload ->> 'total')::NUMERIC(10,2),
    (payload ->> 'items_count')::INTEGER,
    payload ->> 'payment_method'
FROM t7_hw_events
WHERE event_type = 'checkout';

CREATE INDEX idx_t7_checkouts_norm_pm
ON t7_hw_checkouts_norm (payment_method);

ANALYZE t7_hw_checkouts_norm;
""")

display(read_df("SELECT COUNT(*) AS n_checkouts FROM t7_hw_checkouts_norm"))

   n_checkouts
0        10000

### JSONB aggregate query plan

In [25]:
display(read_df("""
EXPLAIN (ANALYZE, BUFFERS)
SELECT
    payload ->> 'payment_method' AS payment_method,
    AVG((payload ->> 'total')::NUMERIC) AS avg_total,
    COUNT(*) AS n
FROM t7_hw_events
WHERE event_type = 'checkout'
GROUP BY payload ->> 'payment_method'
ORDER BY avg_total DESC
LIMIT 3
"""))

                                           QUERY PLAN
0   Limit  (cost=1955.82..1955.83 rows=3 width=72)...
1                            Buffers: shared hit=1000
2     ->  Sort  (cost=1955.82..1969.73 rows=5563 w...
3           Sort Key: (avg(((payload ->> 'total'::...
4                Sort Method: quicksort  Memory: 25kB
5                            Buffers: shared hit=1000
6           ->  HashAggregate  (cost=1800.47..1883...
7                 Group Key: (payload ->> 'payment...
8                     Batches: 1  Memory Usage: 217kB
9                            Buffers: shared hit=1000
10                ->  Seq Scan on t7_hw_events  (c...
11                      Filter: (event_type = 'che...
12                      Rows Removed by Filter: 40000
13                           Buffers: shared hit=1000
14                                          Planning:
15                      Buffers: shared hit=15 read=1
16                            Planning Time: 0.337 ms
17                          Execution Time: 13.895 ms

### Normalized aggregate query plan

In [26]:
display(read_df("""
EXPLAIN (ANALYZE, BUFFERS)
SELECT
    payment_method,
    AVG(total) AS avg_total,
    COUNT(*) AS n
FROM t7_hw_checkouts_norm
GROUP BY payment_method
ORDER BY avg_total DESC
LIMIT 3
"""))

                                           QUERY PLAN
0   Limit  (cost=269.06..269.07 rows=3 width=46) (...
1                              Buffers: shared hit=94
2     ->  Sort  (cost=269.06..269.07 rows=3 width=...
3                         Sort Key: (avg(total)) DESC
4                Sort Method: quicksort  Memory: 25kB
5                              Buffers: shared hit=94
6           ->  HashAggregate  (cost=269.00..269.0...
7                           Group Key: payment_method
8                      Batches: 1  Memory Usage: 24kB
9                              Buffers: shared hit=94
10                ->  Seq Scan on t7_hw_checkouts_...
11                             Buffers: shared hit=94
12                                          Planning:
13                              Buffers: shared hit=3
14                            Planning Time: 0.143 ms
15                           Execution Time: 9.813 ms

### Bonus — MongoDB-equivalent pseudocode

This is pseudocode for comparison only; it is not executable PostgreSQL SQL.

```javascript
db.events.aggregate([
  {$match: {event_type: "checkout"}},
  {$group: {
    _id: "$payload.payment_method",
    avg_total: {$avg: {$toDouble: "$payload.total"}},
    n: {$sum: 1}
  }},
  {$sort: {avg_total: -1}},
  {$limit: 3}
]);
```

PostgreSQL JSONB is useful when events must integrate with SQL, joins,
transactions, and relational data. A document database can be natural
for document-first workloads. Curated ML features are often easier to
validate and query in typed SQL tables.

## 7. Reflection — complete after running the notebook

Write approximately **250–300 words** using the actual query-plan outputs.

Address all five points:

1. Compare `cost`, `actual time`, rows, buffers, and scan operators before and after GIN.
2. Explain why GIN supports JSONB containment but may not be the best index for `payload ->> 'device' = 'mobile'`.
3. Discuss the read/write trade-off and storage overhead of indexes.
4. Compare flexible JSONB payloads with normalized typed columns and constraints.
5. Explain how adding a `refund` event type differs between JSONB and normalized designs.

Do not invent timing figures. PostgreSQL may choose a sequential scan when it estimates that to be cheaper.

### Observed plan notes

Fill these in from your actual outputs:

- Containment before GIN: `[scan type, actual time, buffers]`
- Containment after GIN: `[scan type, actual time, buffers]`
- Device equality before expression index: `[scan type, actual time, buffers]`
- Device equality after expression index: `[scan type, actual time, buffers]`
- JSONB versus normalized aggregate: `[actual plan/time comparison]`

## 8. Final verification checklist

Run the entire notebook after **Runtime → Restart session and run all**.
Keep the resulting SQL outputs in the saved notebook.

In [27]:
summary = read_df("""
SELECT
    (SELECT COUNT(*) FROM t7_hw_taxi_daily) AS taxi_daily_rows,
    (SELECT COUNT(*) FROM v_t7_hw_taxi_features) AS feature_rows,
    (SELECT COUNT(*) FROM t7_hw_events) AS event_rows,
    (SELECT COUNT(DISTINCT event_type) FROM t7_hw_events) AS event_types,
    (SELECT COUNT(*) FROM t7_hw_checkouts_norm) AS normalized_checkout_rows
""")

display(summary)

assert int(summary.loc[0, "taxi_daily_rows"]) > 100
assert int(summary.loc[0, "event_rows"]) >= 50000
assert int(summary.loc[0, "event_types"]) >= 5
assert int(summary.loc[0, "normalized_checkout_rows"]) > 0

print("Core data checks passed.")
print("Data source:", "Official NYC TLC" if USE_REAL_DATA else "Synthetic fallback")

,taxi_daily_rows,feature_rows,event_rows,event_types,normalized_checkout_rows
0,1217,0,50000,5,10000

Core data checks passed.
Data source: Official NYC TLC